server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/reservation_schema
    username: reservation-app
    password: password
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/reservation_schema
    user: reservation-app
    password: password
