services:
  db:
    image: mysql:lts
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=reservation_schema
      - MYSQL_USER=reservation-app
      - MYSQL_PASSWORD=password
    networks:
      - reservation-net
    healthcheck:
      test: [ "CMD", "mysql", "-u", "root", "-proot", "--execute", "SHOW DATABASES;" ]
      interval: 3s
      retries: 5
      timeout: 5s

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - reservation-net

  reservation-api:
    image: azki/reservation-api:0.0.1
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=reservation_schema
      - DB_USERNAME=reservation-app
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - reservation-net
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

networks:
  reservation-net:
    driver: bridge